doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded

        QuiqueGilB\GrowPro\MainContext\RentModule\Infrastructure\Persistence\Doctrine\Migration: '%kernel.project_dir%/src/MainContext/RentModule/Infrastructure/Persistence/Doctrine/Migration'

    enable_profiler: false
