framework:
    messenger:
        default_bus: messenger.bus.blank
        buses:

            messenger.bus.null:
                middleware:
                default_middleware:
                    enabled: false
                    allow_no_handlers: true
                    allow_no_senders: true

            messenger.bus.blank:

            messenger.bus.command.sync:
                middleware:
                    - doctrine_close_connection
                    - doctrine_transaction
            messenger.bus.command.async:
                middleware:
                    - doctrine_close_connection
                    - doctrine_transaction

            messenger.bus.query:
                middleware:
                    - doctrine_close_connection

            messenger.bus.event:
                default_middleware:
                    enabled: true
                    allow_no_handlers: true
                    allow_no_senders: true
                middleware:

        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
