version: "3.9"

x-growpro: &growpro
  build:
    context: ./
    dockerfile: iac/docker/php/Dockerfile
    target: final
    args:
      with-dev-experience: 1
  restart: always
  depends_on:
    - database-dev
    - database-test
  volumes:
    - ./:/app
  networks:
    - growpro-private
  environment:
    PHP_IDE_CONFIG: 'serverName=quiquegilb.growpro'

services:
  php:
    <<: *growpro
    profiles: ["growpro-blank"]
    command: exit 0

  growpro-api:
    <<: *growpro
    command: "symfony server:start --no-tls --allow-http --port=8000 --dir=public"
    networks:
      - growpro-private
      - growpro-public
    ports:
      - "8000:8000"

  database-dev:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-growpro}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-growpro}
      POSTGRES_USER: ${POSTGRES_USER:-growpro}
    volumes:
      - database-dev-data:/var/lib/postgresql/data:rw
    ports:
      - "8002:5432"
    networks:
      - growpro-private

  database-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-growpro}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-growpro}
      POSTGRES_USER: ${POSTGRES_USER:-growpro}
    volumes:
      - database-test-data:/var/lib/postgresql/data:rw
    networks:
      - growpro-private

networks:
  growpro-public:
    name: growpro-public
  growpro-private:
    name: growpro-private

volumes:
  database-dev-data:
  database-test-data:
